version: 2
updates:
  - package-ecosystem: "npm" # Kullandığınız paket yöneticisi (npm, yarn, pip, etc.)
    directory: "/ui" # Projenizin kök dizini. Alt dizinler için değiştirin. (Örneğin: `/backend`)
    schedule:
      interval: "daily" # Güncelleme sıklığı (daily, weekly, monthly)
